version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    expose:
      - 8000
      - 8001
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      DATABASE_URL: 'postgres://hello:django@data:5432/yashoes'
      CACHE_URL: 'redis://cache:6379/'
      STORAGE_URL: 's3:9000'
    links:
      - data:data
      - cache:cache
      - s3:s3
    command: [ "python", "manage.py", "runserver", "--settings=myproject.settings_myapp", "0.0.0.0:8000" ]

  data:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'default'
      POSTGRES_USER: 'hello'
      POSTGRES_PASSWORD: 'django'
    restart: always
    volumes:
      - ./.tmp/data:/var/lib/postgresql/data

  cache:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379
    restart: always
  
  s3:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: 'MINIOACCESSKEYEXAMPLE'
      MINIO_SECRET_KEY: 'MINIOSECRETKEYEXAMPLE'
      MINIO_REGION: 'ap-northeast-1'
    ports:
      - 9000:9000
    volumes:
      - ./.tmp/photo:/export
    command: server /export

  cronjob:
    build:
      context: .
      dockerfile: Dockerfile_cronjob.dev
    volumes:
      - .:/code
      - ./client/
    expose:
      - 8000
    ports:
      - 8888:8000
    environment:
      DATABASE_URL: 'postgres://hello:django@data:5432/yashoes'
      CACHE_URL: 'redis://cache:6379/'
      STORAGE_URL: 's3:9000'
    links:
      - data:data
      - cache:cache
      - s3:s3