# Generated by Django 2.1.5 on 2019-01-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='findmatch',
            unique_together=set(),
        ),
    ]
