# Generated by Django 2.1.5 on 2019-01-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronjobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('job_schedule', models.CharField(max_length=20)),
                ('job_path', models.CharField(max_length=500)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(0, 'init'), (1, 'running'), (2, 'success'), (3, 'fail')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cronjob',
            },
        ),
    ]
