# Generated by Django 2.1.5 on 2019-01-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190128_0818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='findmatch',
            unique_together={('team', 'date_match', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('find_match_a', 'find_match_b', 'date_match', 'status')},
        ),
    ]
