# Generated by Django 2.1.5 on 2019-01-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190128_0818'),
        ('myapp', '0002_cronjobmodel'),
    ]

    operations = [
    ]
