# Generated by Django 2.1.5 on 2019-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190115_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findmatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Peding'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=2),
        ),
        migrations.AlterField(
            model_name='stadiumregister',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Peding'), ('PAID', 'Paid'), ('CANCEL', 'Cancel')], default='PENDING', max_length=2),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Peding'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=2),
        ),
    ]
