# Generated by Django 2.1.5 on 2019-01-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20190129_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'running'), (2, 'success'), (3, 'fail')], default=0),
        ),
    ]
