# Generated by Django 2.1.5 on 2019-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cronjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findmatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITING', 'Waiting')], default='PENDING', max_length=10),
        ),
    ]
